# jobs sequense pipeline
stages:
  - deploy-dev

# deploy job
deploy-dev:
  tags:
    - star-cactus
  script:
    - echo "====== Deploy to demo server ======"
    - yarn add pm2 --ignore-engines
    # Initialize the remote folder with:
    - echo "Setup target server directories"
    - pm2 deploy ecosystem.dev.config.js development setup 2>&1 || true
    # Delploy
    - echo "make deploy"
    - pm2 deploy ecosystem.dev.config.js development --force
  stage: deploy-dev
  only:
    - dev
